INSERT INTO "event"("code","sports","name","gender","players")VALUES(20000,'Archery','Individual','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20001,'Archery','Individual','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20002,'Archery','Team','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20003,'Archery','Team','W',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20004,'Athletics','10 km Walk','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20005,'Athletics','100 m Hurdles','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20006,'Athletics','10000m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20007,'Athletics','10000m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20008,'Athletics','100m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20009,'Athletics','100m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20010,'Athletics','110m Hurdles','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20011,'Athletics','110m Hurdles','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20012,'Athletics','1500m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20013,'Athletics','1500m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20014,'Athletics','1500m Wheelchair','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20015,'Athletics','200m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20016,'Athletics','200m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20017,'Athletics','20km Walk','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20018,'Athletics','20km Walk','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20019,'Athletics','3000m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20020,'Athletics','3000m Steeplechase','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20021,'Athletics','4 x 100m Relay','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20022,'Athletics','4 x 100m Relay','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20023,'Athletics','4 x 400m Relay','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20024,'Athletics','4 x 400m Relay','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20025,'Athletics','400m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20026,'Athletics','400m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20027,'Athletics','400m Hurdles','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20028,'Athletics','400m Hurdles','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20029,'Athletics','5000m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20030,'Athletics','5000m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20031,'Athletics','50km Walk','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20032,'Athletics','800m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20033,'Athletics','800m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20034,'Athletics','800m Wheelchair','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20035,'Athletics','Decathlon','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20036,'Athletics','Discus Throw','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20037,'Athletics','Discus Throw','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20038,'Athletics','Hammer Throw','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20039,'Athletics','Hammer Throw','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20040,'Athletics','Heptathlon','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20041,'Athletics','High Jump','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20042,'Athletics','High Jump','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20043,'Athletics','Javelin Throw','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20044,'Athletics','Javelin Throw','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20045,'Athletics','Long Jump','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20046,'Athletics','Long Jump','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20047,'Athletics','Marathon','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20048,'Athletics','Marathon','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20049,'Athletics','Pole Vault','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20050,'Athletics','Pole Vault','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20051,'Athletics','Shot put','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20052,'Athletics','Shot Put','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20053,'Athletics','Triple Jump','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20054,'Athletics','Triple Jump','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20055,'Badminton','Doubles','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20056,'Badminton','Doubles','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20057,'Badminton','Doubles','X',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20058,'Badminton','Singles','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20059,'Badminton','Singles','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20060,'Baseball','Baseball','M',9);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20061,'Basketball','Basketball','M',5);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20062,'Basketball','Basketball','W',5);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20063,'Boxing','+91kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20064,'Boxing','48kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20065,'Boxing','51kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20066,'Boxing','54kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20067,'Boxing','57kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20068,'Boxing','60kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20069,'Boxing','63.5kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20070,'Boxing','64kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20071,'Boxing','67kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20072,'Boxing','69kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20073,'Boxing','71kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20074,'Boxing','75kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20075,'Boxing','81kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20076,'Boxing','91kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20077,'Canoe','Double','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20078,'Canoe','Double 1000m','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20079,'Canoe','Double 500m','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20080,'Canoe','Single','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20081,'Canoe','Single 1000m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20082,'Canoe','Single 500m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20083,'Cycling','100km Time Trial','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20084,'Cycling','1km Time Trial','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20085,'Cycling','500m Time Trial','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20086,'Cycling','Cross Country','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20087,'Cycling','Cross Country','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20088,'Cycling','Individual Pursuit','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20089,'Cycling','Individual Pursuit','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20090,'Cycling','Individual Time Trial','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20091,'Cycling','Individual Time Trial','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20092,'Cycling','Keirin','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20093,'Cycling','Madison','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20094,'Cycling','Olympic Sprint','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20095,'Cycling','Points Race','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20096,'Cycling','Points Race','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20097,'Cycling','Road Race','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20098,'Cycling','Road Race','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20099,'Cycling','Sprint','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20100,'Cycling','Sprint','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20101,'Cycling','Team Pursuit','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20102,'Cycling','Team Sprint','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20103,'Diving','10m Platform','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20104,'Diving','10m Platform','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20105,'Diving','3m Springboard','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20106,'Diving','3m Springboard','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20107,'Diving','Synchronized 10m Platform','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20108,'Diving','Synchronized 10m Platform','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20109,'Diving','Synchronized 3m Springboard','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20110,'Diving','Synchronized 3m Springboard','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20111,'Equestrian','Individual Dressage','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20112,'Equestrian','Individual Five-Day Event','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20113,'Equestrian','Individual Four-Day Event','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20114,'Equestrian','Individual Jumping','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20115,'Equestrian','Individual Three-Day Event','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20116,'Equestrian','Team Dressage','X',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20117,'Equestrian','Team Jumping','X',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20118,'Equestrian','Team Three-Day Event','X',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20119,'Fencing','Individual Epee','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20120,'Fencing','Individual Epee','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20121,'Fencing','Individual Foil','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20122,'Fencing','Individual Foil','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20123,'Fencing','Individual Sabre','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20124,'Fencing','Individual Sabre','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20125,'Fencing','Team Epee','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20126,'Fencing','Team Epee','W',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20127,'Fencing','Team Foil','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20128,'Fencing','Team Foil','W',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20129,'Fencing','Team Sabre','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20130,'Football','Football','M',11);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20131,'Football','Football','W',11);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20132,'Gymnastics','Artistic Asymmetric bars','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20133,'Gymnastics','Artistic Individual All-Around','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20134,'Gymnastics','Artistic Individual All-Around','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20135,'Gymnastics','Artistic Individual Apparatus','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20136,'Gymnastics','Artistic Individual Apparatus','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20137,'Gymnastics','Artistic Team','M',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20138,'Gymnastics','Artistic Team','W',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20139,'Gymnastics','beam','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20140,'Gymnastics','beam','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20141,'Gymnastics','Floor Exercise','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20142,'Gymnastics','Floor Exercise','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20143,'Gymnastics','Horizontal Bar','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20144,'Gymnastics','Parallel Bars','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20145,'Gymnastics','Pommel Horse','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20146,'Gymnastics','Rhythmic Group Competition','W',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20147,'Gymnastics','Rhythmic Individual All-Around','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20148,'Gymnastics','Rhythmic individual Competition','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20149,'Gymnastics','Rhythmic individual Competition','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20150,'Gymnastics','Rhythmic Team','M',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20151,'Gymnastics','Rhythmic Team','W',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20152,'Gymnastics','Rings','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20153,'Gymnastics','Team','M',12);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20154,'Gymnastics','Team','W',12);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20155,'Gymnastics','Trampoline','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20156,'Gymnastics','Trampoline','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20157,'Gymnastics','Uneven Bars','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20158,'Gymnastics','Vault','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20159,'Gymnastics','Vault','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20160,'Handball','Handball','M',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20161,'Handball','Handball','W',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20162,'Hockey','Hockey','M',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20163,'Hockey','Hockey','W',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20164,'Judo','+100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20165,'Judo','+72kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20166,'Judo','+78kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20167,'Judo','+95kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20168,'Judo','-100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20169,'Judo','-48kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20170,'Judo','-52kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20171,'Judo','-56Kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20172,'Judo','-57kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20173,'Judo','60-66kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20174,'Judo','-60kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20175,'Judo','-61kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20176,'Judo','-63kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20177,'Judo','-65kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20178,'Judo','66-73kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20179,'Judo','-66kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20180,'Judo','-66kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20181,'Judo','-70kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20182,'Judo','-71kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20183,'Judo','-72kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20184,'Judo','73-81kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20185,'Judo','-73kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20186,'Judo','-78kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20187,'Judo','-78kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20188,'Judo','81-90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20189,'Judo','-81kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20190,'Judo','-86kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20191,'Judo','90-100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20192,'Judo','-90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20193,'Judo','-95kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20194,'Kayak','Double 1000m','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20195,'Kayak','Double 500m','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20196,'Kayak','Double 500m','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20197,'Kayak','Four 1000m','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20198,'Kayak','Four 500m','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20199,'Kayak','Single','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20200,'Kayak','Single','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20201,'Kayak','Single 1000m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20202,'Kayak','Single 500m','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20203,'Kayak','Single 500m','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20204,'Modern Pentathlon','Individual','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20205,'Modern Pentathlon','Individual','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20206,'Modern Pentathlon','Team','M',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20207,'Rowing','Coxless Four','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20208,'Rowing','Coxless Four','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20209,'Rowing','Coxless Pair','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20210,'Rowing','Coxless Pair','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20211,'Rowing','Double Sculls','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20212,'Rowing','Double Sculls','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20213,'Rowing','Eight','M',8);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20214,'Rowing','Eight','W',8);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20215,'Rowing','Four oars with coxswain','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20216,'Rowing','Lightweight Coxless Four','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20217,'Rowing','Lightweight Double Sculls','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20218,'Rowing','Lightweight Double Sculls','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20219,'Rowing','Pair oars with coxwain','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20220,'Rowing','Quadruple Sculls','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20221,'Rowing','Quadruple Sculls','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20222,'Rowing','Single Sculls','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20223,'Rowing','Single Sculls','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20224,'Sailing','470','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20225,'Sailing','470','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20226,'Sailing','49er','X',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20227,'Sailing','Division II','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20228,'Sailing','Europe','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20229,'Sailing','Finn','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20230,'Sailing','Flying Dutchman','X',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20231,'Sailing','Laser','X',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20232,'Sailing','Lechner A-390','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20233,'Sailing','Mistral','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20234,'Sailing','Mistral','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20235,'Sailing','Soiling','X',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20236,'Sailing','Star','X',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20237,'Sailing','Tornado','X',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20238,'Sailing','yngling','W',3);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20239,'Shooting','10m Air Pistol','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20240,'Shooting','10m Air Pistol','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20241,'Shooting','10m Air Rifle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20242,'Shooting','10m Air Rifle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20243,'Shooting','10m Running Target','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20244,'Shooting','25 m Rapid Fire Pistol','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20245,'Shooting','25m Pistol','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20246,'Shooting','25m Rapid Fire Pistol','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20247,'Shooting','50m Free Pistol','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20248,'Shooting','50m Free Rifle 3 Position','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20249,'Shooting','50m Free Rifle Prone','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20250,'Shooting','50m Standard Rifle 3 Position','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20251,'Shooting','Double Trap','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20252,'Shooting','Double Trap','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20253,'Shooting','Skeet','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20254,'Shooting','Skeet','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20255,'Shooting','Sport pistol','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20256,'Shooting','Trap','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20257,'Shooting','Trap','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20258,'Softball','Softball','W',9);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20259,'Swimming','100m Backstroke','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20260,'Swimming','100m Backstroke','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20261,'Swimming','100m Breaststroke','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20262,'Swimming','100m Breaststroke','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20263,'Swimming','100m Butterfly','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20264,'Swimming','100m Butterfly','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20265,'Swimming','100m Freestyle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20266,'Swimming','100m Freestyle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20267,'Swimming','1500m Freestyle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20268,'Swimming','200m Backstroke','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20269,'Swimming','200m Backstroke','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20270,'Swimming','200m Breaststroke','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20271,'Swimming','200m Breaststroke','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20272,'Swimming','200m Butterfly','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20273,'Swimming','200m Butterfly','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20274,'Swimming','200m Freestyle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20275,'Swimming','200m Freestyle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20276,'Swimming','200m Individual Medley','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20277,'Swimming','200m Individual Medley','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20278,'Swimming','4 x 100m Freestyle Relay','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20279,'Swimming','4 x 100m Freestyle Relay','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20280,'Swimming','4 x 100m Medley Relay','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20281,'Swimming','4 x 100m Medley Relay','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20282,'Swimming','4 x 200m Freestyle Relay','M',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20283,'Swimming','4 x 200m Freestyle Relay','W',4);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20284,'Swimming','400m Freestyle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20285,'Swimming','400m Freestyle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20286,'Swimming','400m Individual Medley','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20287,'Swimming','400m Individual Medley','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20288,'Swimming','50m Freestyle','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20289,'Swimming','50m Freestyle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20290,'Swimming','800m Freestyle','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20291,'Swimming','Synchronized Duet','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20292,'Swimming','Synchronized Solo','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20293,'Swimming','Synchronized Team','W',8);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20294,'Table Tennis','Double','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20295,'Table Tennis','Double','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20296,'Table Tennis','Single','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20297,'Table Tennis','Single','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20298,'Taekwondo','over 67kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20299,'Taekwondo','over 80kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20300,'Taekwondo','Under 49kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20301,'Taekwondo','Under 57kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20302,'Taekwondo','Under 58kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20303,'Taekwondo','Under 67kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20304,'Taekwondo','Under 68kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20305,'Taekwondo','Under 80kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20306,'Tennis','Double','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20307,'Tennis','Double','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20308,'Tennis','Single','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20309,'Tennis','Single','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20310,'Triathlon','Triathlon','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20311,'Triathlon','Triathlon','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20312,'Volleyball','Beach','M',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20313,'Volleyball','Beach','W',2);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20314,'Volleyball','Indoor','M',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20315,'Volleyball','Indoor','W',6);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20316,'Water Polo','Water Polo','M',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20317,'Water Polo','Water Polo','W',7);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20318,'Weightlifting','+105kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20319,'Weightlifting','+108kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20320,'Weightlifting','+110kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20321,'Weightlifting','+75kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20322,'Weightlifting','100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20323,'Weightlifting','105kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20324,'Weightlifting','108kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20325,'Weightlifting','110kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20326,'Weightlifting','48kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20327,'Weightlifting','52kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20328,'Weightlifting','53kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20329,'Weightlifting','54kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20330,'Weightlifting','56kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20331,'Weightlifting','58kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20332,'Weightlifting','59kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20333,'Weightlifting','60kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20334,'Weightlifting','62kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20335,'Weightlifting','63kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20336,'Weightlifting','64kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20337,'Weightlifting','67.5kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20338,'Weightlifting','69kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20339,'Weightlifting','69kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20340,'Weightlifting','70kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20341,'Weightlifting','75kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20342,'Weightlifting','75kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20343,'Weightlifting','76kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20344,'Weightlifting','77kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20345,'Weightlifting','82.5kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20346,'Weightlifting','83kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20347,'Weightlifting','85kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20348,'Weightlifting','90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20349,'Weightlifting','91kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20350,'Weightlifting','94kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20351,'Weightlifting','99kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20352,'Wrestling','Freestyle 100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20353,'Wrestling','Freestyle -100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20354,'Wrestling','Freestyle 120kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20355,'Wrestling','Freestyle 130kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20356,'Wrestling','Freestyle -130kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20357,'Wrestling','Freestyle 48kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20358,'Wrestling','Freestyle 48kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20359,'Wrestling','Freestyle -48kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20360,'Wrestling','Freestyle 52kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20361,'Wrestling','Freestyle -52kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20362,'Wrestling','Freestyle 54kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20363,'Wrestling','Freestyle 55kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20364,'Wrestling','Freestyle 55kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20365,'Wrestling','Freestyle 57kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20366,'Wrestling','Freestyle -57kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20367,'Wrestling','Freestyle 58kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20368,'Wrestling','Freestyle 60kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20369,'Wrestling','Freestyle 62kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20370,'Wrestling','Freestyle -62kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20371,'Wrestling','Freestyle 63kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20372,'Wrestling','Freestyle 63kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20373,'Wrestling','Freestyle 66kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20374,'Wrestling','Freestyle 68kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20375,'Wrestling','Freestyle -68kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20376,'Wrestling','Freestyle 69kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20377,'Wrestling','Freestyle 72kg','W',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20378,'Wrestling','Freestyle 74kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20379,'Wrestling','Freestyle -74kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20380,'Wrestling','Freestyle 76kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20381,'Wrestling','Freestyle 82kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20382,'Wrestling','Freestyle -82kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20383,'Wrestling','Freestyle 84kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20384,'Wrestling','Freestyle 85kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20385,'Wrestling','Freestyle 90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20386,'Wrestling','Freestyle -90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20387,'Wrestling','Freestyle 96kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20388,'Wrestling','Freestyle 97kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20389,'Wrestling','Greco-Roman -100 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20390,'Wrestling','Greco-Roman 100kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20391,'Wrestling','Greco-Roman 120kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20392,'Wrestling','Greco-Roman -130 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20393,'Wrestling','Greco-Roman 130kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20394,'Wrestling','Greco-Roman -48 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20395,'Wrestling','Greco-Roman 48kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20396,'Wrestling','Greco-Roman -52 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20397,'Wrestling','Greco-Roman 52kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20398,'Wrestling','Greco-Roman 54kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20399,'Wrestling','Greco-Roman 55kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20400,'Wrestling','Greco-Roman -57 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20401,'Wrestling','Greco-Roman 57kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20402,'Wrestling','Greco-Roman 58kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20403,'Wrestling','Greco-Roman 60kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20404,'Wrestling','Greco-Roman -62 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20405,'Wrestling','Greco-Roman 62kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20406,'Wrestling','Greco-Roman 63kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20407,'Wrestling','Greco-Roman 66kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20408,'Wrestling','Greco-Roman -68 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20409,'Wrestling','Greco-Roman 68kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20410,'Wrestling','Greco-Roman 69kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20411,'Wrestling','Greco-Roman -74 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20412,'Wrestling','Greco-Roman 74kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20413,'Wrestling','Greco-Roman 76kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20414,'Wrestling','Greco-Roman -82 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20415,'Wrestling','Greco-Roman 82kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20416,'Wrestling','Greco-Roman 84kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20417,'Wrestling','Greco-Roman 85kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20418,'Wrestling','Greco-Roman -90 kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20419,'Wrestling','Greco-Roman 90kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20420,'Wrestling','Greco-Roman 96kg','M',1);
INSERT INTO "event"("code","sports","name","gender","players")VALUES(20421,'Wrestling','Greco-Roman 97kg','M',1);
