INSERT INTO "nation"("code","name","continent","capital")VALUES('AFG','Afghanistan','Asia','Kabul');
INSERT INTO "nation"("code","name","continent","capital")VALUES('AHO','Netherlands Antilles','Americas','Willemstad');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ALB','Albania','Europe','Tirana');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ALG','Algeria','Africa','Algiers');
INSERT INTO "nation"("code","name","continent","capital")VALUES('AND','Andorra','Europe','Andorra la Vella');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ANG','Angola','Africa','Luanda');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ANT','Antigua & Barbuda','Americas','Saint John''s');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ARG','Argentina','Americas','Buenos Aires');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ARM','Armenia','Europe','Yerevan');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ARU','Aruba','Americas','Oranjestad');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ASA','American Samoa','Oceania','Pago Pago');
INSERT INTO "nation"("code","name","continent","capital")VALUES('AUS','Australia','Oceania','Canberra');
INSERT INTO "nation"("code","name","continent","capital")VALUES('AUT','Austria','Europe','Vienna');
INSERT INTO "nation"("code","name","continent","capital")VALUES('AZE','Azerbaijan','Europe','Baku');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BAH','Bahamas','Americas','Nassau');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BAN','Bangladesh','Asia','Dhaka');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BAR','Barbados','Americas','Bridgetown');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BDI','Burundi','Africa','Bujumbura');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BEL','Belgium','Europe','Brussels');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BEN','Benin','Africa','Porto-Novo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BER','Bermuda','Americas','Hamilton');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BHU','Bhutan','Asia','Thimphu');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BIH','Bosnia & Herzegovina','Europe','Sarajevo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BIR','Burma','Asia','');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BIZ','Belize','Americas','Belmopan');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BLR','Belarus','Europe','Minsk');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BOL','Bolivia','Americas','Sucre');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BOT','Botswana','Africa','Gaborone');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BRA','Brazil','Americas','Brasilia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BRN','Bahrain','Asia','Manama');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BRU','Brunei Darussalam','Asia','Bandar Seri Begawan');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BUL','Bulgaria','Europe','Sofia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('BUR','Burkina Faso','Africa','Ouagadougou');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CAF','Central African Republic','Africa','Bangui');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CAM','Cambodia','Asia','Phnom Penh');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CAN','Canada','Americas','Ottawa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CAY','Cayman Islands','Americas','George Town');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CGO','Congo','Africa','Brazzaville');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CHA','Chad','Africa','N''djamena');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CHI','Chile','Americas','Santiago');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CHN','People''s Republic of China','Asia','Beijing');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CIV','Cote dlvoire','Africa','Yamoussoukro');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CMR','Cameroon','Africa','Yaounde');
INSERT INTO "nation"("code","name","continent","capital")VALUES('COD','Democratic Republic of the Congo','Africa','Kinshasa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('COK','CookIslands','Oceania','Avarua');
INSERT INTO "nation"("code","name","continent","capital")VALUES('COL','Colombia','Americas','Bogota');
INSERT INTO "nation"("code","name","continent","capital")VALUES('COM','Comoros','Africa','Moroni');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CPV','Cape Verde','Africa','Praia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CRC','Costa Rica','Americas','San Jose');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CRO','Croatia','Europe','Zagreb');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CUB','Cuba','Americas','Havana');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CYP','Cyprus','Europe','Nicosia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('CZE','Czech Republic','Europe','Prague');
INSERT INTO "nation"("code","name","continent","capital")VALUES('DEN','Denmark','Europe','Copenhagen');
INSERT INTO "nation"("code","name","continent","capital")VALUES('DJI','Djibouti','Africa','Djibouti');
INSERT INTO "nation"("code","name","continent","capital")VALUES('DMA','Dominica','Americas','Roseau');
INSERT INTO "nation"("code","name","continent","capital")VALUES('DOM','Dominican Republic','Americas','Santo Domingo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ECU','Ecuador','Americas','Quito');
INSERT INTO "nation"("code","name","continent","capital")VALUES('EGY','Arab Republic of Egypt','Africa','Cairo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ERI','Eritrea','Africa','Asmara');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ESA','El Salvador','Americas','San Salvador');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ESP','Spain','Europe','Madrid');
INSERT INTO "nation"("code","name","continent","capital")VALUES('EST','Estonia','Europe','Tallinn');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ETH','Ethiopia','Africa','Addis Ababa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('EUN','Unified Team','','');
INSERT INTO "nation"("code","name","continent","capital")VALUES('FIJ','Fiji','Oceania','Suva');
INSERT INTO "nation"("code","name","continent","capital")VALUES('FIN','Finland','Europe','Helsinki');
INSERT INTO "nation"("code","name","continent","capital")VALUES('FRA','France','Europe','Paris');
INSERT INTO "nation"("code","name","continent","capital")VALUES('FRG','Federal Republic of Germany','Europe','Bonn');
INSERT INTO "nation"("code","name","continent","capital")VALUES('FSM','Federated States of Micronesia','Oceania','Palikir');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GAB','Gabon','Africa','Libreville');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GAM','Gambia','Africa','Banjul');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GBR','Great Britain','Europe','London');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GBS','Guinea-Bissau','Africa','Bissau');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GDR','German Democratic Republic','Europe','East Berlin');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GEO','Georgia','Europe','Tbilisi');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GEQ','Equatorial Guinea','Africa','Malabo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GER','Germany','Europe','Berlin');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GHA','Ghana','Africa','Accra');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GRE','Greece','Europe','Athens');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GRN','Grenada','Americas','Saint George''s');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GUA','Guatemala','Americas','Guatemala City');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GUI','Guinea','Africa','Conakry');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GUM','Guam','Oceania','Hagatha');
INSERT INTO "nation"("code","name","continent","capital")VALUES('GUY','Guyana','Americas','Georgrtown');
INSERT INTO "nation"("code","name","continent","capital")VALUES('HAI','Haiti','Americas','Port-au-Prince');
INSERT INTO "nation"("code","name","continent","capital")VALUES('HKG','Hong Kong','Asia','');
INSERT INTO "nation"("code","name","continent","capital")VALUES('HON','Honduras','Americas','Tegucigalpa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('HUN','Hungary','Europe','Budapest');
INSERT INTO "nation"("code","name","continent","capital")VALUES('INA','Indonesia','Asia','Jakarta');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IND','India','Asia','New Delhi');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IOA','Individual Olympic Athletes','Other','');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IOP','Independent Olympic Participants','','');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IRI','Iran','Asia','Tehran');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IRL','Ireland','Europe','Dublin');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IRQ','Iraq','Asia','Baghdad');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ISL','Iceland','Europe','Reykjavik');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ISR','Israel','Europe','Jerusalem');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ISV','Virgin Islands','Americas','Road Town');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ITA','Italy','Europe','Rome');
INSERT INTO "nation"("code","name","continent","capital")VALUES('IVB','British Virgin Islands','Americas','Road Town');
INSERT INTO "nation"("code","name","continent","capital")VALUES('JAM','Jamaica','Americas','Kingston');
INSERT INTO "nation"("code","name","continent","capital")VALUES('JOR','Jordan','Asia','Amman');
INSERT INTO "nation"("code","name","continent","capital")VALUES('JPN','Japan','Asia','Tokyo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KAZ','Kazakhstan','Asia','Astana');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KEN','kenya','Africa','Nairobi');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KGZ','Kyrgyzstan','Asia','Bishkek');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KIR','Kiribati','Oceania','Tarawa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KOR','Korea','Asia','Seoul');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KSA','Saudi Arabia','Asia','Riyadh');
INSERT INTO "nation"("code","name","continent","capital")VALUES('KUW','Kuwait','Asia','Kuwait City');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LAO','Lao People''s Democratic Republic','Asia','Vientiane');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LAT','Latvia','Europe','Riga');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LBA','Libyan Arab Jamahiriya','Africa','Tripoli');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LBR','Liberia','Africa','Monrovia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LCA','Saint Lucia','Americas','Castries');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LES','Lesotho','Africa','Maseru');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LIB','Lebanon','Asia','Beirut');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LIE','Liechtenstein','Europe','Vaduz');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LTU','Lithuania','Europe','Vilnius');
INSERT INTO "nation"("code","name","continent","capital")VALUES('LUX','Luxembourg','Europe','Luxembourg');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MAD','Madagascar','Africa','Antananarivo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MAR','Morocco','Africa','Rabat');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MAS','Malaysia','Asia','Kuala Lumpur');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MAW','Malawi','Africa','lilongwe');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MDA','Republic of Mooldova','Europe','Chisinau');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MDV','Maldives','Asia','Male');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MEX','Mexico','Americas','Mexico city');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MGL','Mongolia','Asia','Ulaanbaatar');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MKD','Former Yugoslav Republic of Macedonia','Europe','Skopje');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MLI','Mali','Africa','Bamako');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MLT','Malta','Europe','Valletta');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MON','Monaco','Europe','Monaco');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MOZ','Mozambique','Africa','Maputo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MRI','Mauritius','Africa','Port Louis');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MTN','Mauritania','Africa','Nouakchott');
INSERT INTO "nation"("code","name","continent","capital")VALUES('MYA','Myanmar','Asia','Naypyidaw');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NAM','Nambia','Africa','Windhoek');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NCA','Nicaragua','Americas','Managua');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NED','Netherlands','Europe','Amsterdam');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NEP','Nepal','Asia','Kathmandu');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NGR','Nigeria','Africa','Abuja');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NIG','Niger','Africa','Niamey');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NOR','Norway','Europe','Oslo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NRU','Nauru','Oceania','Yaren');
INSERT INTO "nation"("code","name","continent","capital")VALUES('NZL','New Zealand','Oceania','Wellington');
INSERT INTO "nation"("code","name","continent","capital")VALUES('OMA','Oman','Asia','Muscat');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PAK','Pakistan','Asia','Islambad');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PAN','Panama','Americas','Panama city');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PAR','Paraguay','Americas','Asuncion');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PER','Peru','Americas','Lima');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PHI','Philippines','Asia','Manila');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PLE','Palestine','Asia','Ramallah');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PLW','Palau','Oceania','Melekeok');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PNG','Papua-New Guinea','Oceania','Port Moresby');
INSERT INTO "nation"("code","name","continent","capital")VALUES('POL','Poland','Europe','Warsaw');
INSERT INTO "nation"("code","name","continent","capital")VALUES('POR','Portugal','Europe','Lisbon');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PRK','Democratic People''s Republic of Korea','Asia','Pyeongyang');
INSERT INTO "nation"("code","name","continent","capital")VALUES('PUR','Puerto Rico','Americas','San Juan');
INSERT INTO "nation"("code","name","continent","capital")VALUES('QAT','Qatar','Asia','Doha');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ROU','Romania','Europe','Bucharest');
INSERT INTO "nation"("code","name","continent","capital")VALUES('RSA','South Africa','Africa','Pretoria');
INSERT INTO "nation"("code","name","continent","capital")VALUES('RUS','Russian Federation','Europe','Moscow');
INSERT INTO "nation"("code","name","continent","capital")VALUES('RWA','Rwanda','Africa','Kigali');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SAM','Samoa','Oceania','Apia');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SCG','Serbia and Montenegro','Europe','Beograd');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SEN','Senegal','Africa','Dakar');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SEY','Seychelles','Africa','Victoria');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SIN','Singapore','Asia','Singapore');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SKN','Saint Kitts & Nevis','Americas','Basseterre');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SLE','Sierra Leone','Africa','Freetown');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SLO','Slovenia','Europe','Ljubljana');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SMR','San Marino','Europe','San Marino');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SOL','Solomon Islands','Oceania','Honiara');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SOM','Somalia','Africa','Mogadishu');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SRB','Serbia','Europe','Beograd');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SRI','Sri Lanka','Asia','Sri Jayewardenepura Kotte');
INSERT INTO "nation"("code","name","continent","capital")VALUES('STP','Sao Tome & Principe','Africa','Sao Tome');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SUD','Sudan','Africa','Khartoum');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SUI','Switzerland','Europe','Berne');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SUR','Surinam','Americas','Paramaribo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SVK','Slovakia','Europe','Bratislava');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SWE','Sweden','Europe','Stockholm');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SWZ','Swaziland','Africa','Mbabane');
INSERT INTO "nation"("code","name","continent","capital")VALUES('SYR','Syrian Arab Republic','Asia','Damascus');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TAN','United Republic of Tanzania','Africa','Dodoma');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TCH','Czechoslovakia','Europe','Prague');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TGA','Tonga','Oceania','Nuku''alofa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('THA','Thailand','Asia','Bangkok');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TJK','Tajikistan','Asia','Dushanbe');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TKM','Turmenistan','Asia','Ashgabat');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TLS','Timor-Leste','Asia','Dili');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TOG','Togo','Africa','Lome');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TPE','Taiwan','Asia','Taipei');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TRI','Trinidad and Tobago','Americas','Port of Spain');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TUN','Tunisia','Africa','Tunis');
INSERT INTO "nation"("code","name","continent","capital")VALUES('TUR','Turkey','Europe','Ankara');
INSERT INTO "nation"("code","name","continent","capital")VALUES('UAE','United Arab Emirates','Asia','Abu Dhabi');
INSERT INTO "nation"("code","name","continent","capital")VALUES('UGA','Uganda','Africa','Kampala');
INSERT INTO "nation"("code","name","continent","capital")VALUES('UKR','Ukraine','Europe','Kiev');
INSERT INTO "nation"("code","name","continent","capital")VALUES('URS','U.R.S.S.','Europe','Moscow');
INSERT INTO "nation"("code","name","continent","capital")VALUES('URU','Uruguay','Americas','Montevideo');
INSERT INTO "nation"("code","name","continent","capital")VALUES('USA','United States of America','Americas','Washington.D.C');
INSERT INTO "nation"("code","name","continent","capital")VALUES('UZB','Uzbekistan','Asia','Tashkent');
INSERT INTO "nation"("code","name","continent","capital")VALUES('VAN','Vanuatu','Oceania','Port Vila');
INSERT INTO "nation"("code","name","continent","capital")VALUES('VEN','Venezuela','Americas','Caracas');
INSERT INTO "nation"("code","name","continent","capital")VALUES('VIE','Vietnam','Asia','Hanoi');
INSERT INTO "nation"("code","name","continent","capital")VALUES('VIN','Saint Vincent & the Grenadines','Americas','Kingstown');
INSERT INTO "nation"("code","name","continent","capital")VALUES('YAR','Yemen Arabian Republic','Asia','Sana''a');
INSERT INTO "nation"("code","name","continent","capital")VALUES('YEM','Yemen','Asia','Sana''a');
INSERT INTO "nation"("code","name","continent","capital")VALUES('YMD','Yemen Democratic Republic','Asia','Sana''a');
INSERT INTO "nation"("code","name","continent","capital")VALUES('YUG','Yugoslavia','Europe','Belgrade');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ZAI','Zaire','Africa','Kinshasa');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ZAM','Zambia','Africa','Lusaka');
INSERT INTO "nation"("code","name","continent","capital")VALUES('ZIM','Zimbabwe','Africa','Harare');
