INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30000,'AUS','Blacktown Olympic Centre Aquilina Reserve',75000.,12000,'Blacktown');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30001,'AUS','Baseball Stadium',85000.,21000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30002,'AUS','Beach Volleyball centre, Bondi',34000.,10000,'Bondi Beach');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30003,'AUS','DUNC GRAY VELODROME, BANKSTOWN',67500.,6000,'The Crest of Bankstown');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30004,'AUS','Mountain Bike Course, Fairfield City Farm',76250.,21000,'Fairfield City Farm Abbotsbury');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30005,'AUS','New South Wales Tennis Centre',40000.,10000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30006,'AUS','Olympic Stadium',170000.,115600,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30007,'AUS','Penrith Whitewater Stadium, Penrith Lakes',35000.,8500,'Penrith');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30008,'AUS','Ryde Aquatic Leisure Centre',12000.,3900,'Ryde');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30009,'AUS','Sydney Harbour',40000.,10000,'Rushcutters Bay, New South Wales');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30010,'AUS','Sydney International Shooting Centre, Cecil Park',34000.,7000,'Cecil Park, South West Sydney');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30011,'AUS','State Hockey Centre',32000.,8000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30012,'AUS','State Sports Centre',21000.,5000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30013,'AUS','Sydney Convention and Exhibition Centre',60000.,30000,'Darling Harbour');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30014,'AUS','Sydney Entertainment Centre',34000.,11000,'Darling Harbour');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30015,'AUS','Sydney Football Stadium, Centennial Parklands',27000.,42000,'Moore Park adjacent to Centennial Parklands');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30016,'AUS','Sydney International Aquatic Centre',36400.,17500,'Sydney Olympic Park');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30017,'AUS','Sydney International Archery Park',16000.,4500,'Millennium Parklands, Sydney Olympic Park Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30018,'AUS','Dunc Gray Velodrome, Horsley Park',21000.,50000,'Horsley Park');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30019,'AUS','Sydney International Regatta Centre, Penrith Lakes',60000.,73000,'Penrith Lakes');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30020,'AUS','Sydney Superdome',61000.,21000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30021,'AUS','The Dome',53000.,10000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30022,'AUS','Pavilion 2',20000.,6000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30023,'AUS','Pavilion 3',21000.,6000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30024,'AUS','Pavilion 4',20000.,6000,'Sydney Olympic Park, Homebush Bay');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30025,'AUS','Brisbane Cricket Ground, Brisbane',34000.,37000,'Brisbane Queensland');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30026,'AUS','Bruce Stadium, Canberra',64000.,40000,'Canberra ACT');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30027,'AUS','Hindmarsh Stadium, Adelaide',31000.,20000,'Hindmarsh, Adelaide');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30028,'AUS','Melbourne Cricket Ground, Melbourne',110000.,98000,'Yarra Park');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30029,'USA','Alexander Memorial Coliseum',71500.,9191,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30030,'USA','Atlanta Beach',21000.,12600,'Jonesboro, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30031,'USA','Atlanta-Fulton Country Stadium ',110000.,54000,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30032,'USA','Clark Atlanta University',10000.,5000,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30033,'USA','Florida Citrus Bowl',87000.,65000,'Olrando, Florida');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30034,'USA','Georgia Dome',50000.,34500,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30035,'USA','Georgia International Horse Park',48000.,32000,'Conyers, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30036,'USA','Georgia State University Gymnasium',11000.,3500,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30037,'USA','Georgia Tech Aquatic Center',45000.,15000,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30038,'USA','Georgia World Congress Center',130000.,60000,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30039,'USA','Golden Park',37520.,8800,'Columbus, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30040,'USA','Lake Lanier',36500.,17300,'Gainsesville, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30041,'USA','Legion Field',25000.,81700,'Birminghan, Alabama');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30042,'USA','Road Courses',87500.,800,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30043,'USA','Morehouse College Gymnasium',35600.,6000,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30044,'USA','Ocoee Whitewater Center',34650.,14400,'Ocoee River, Tennessee');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30045,'USA','Olympic Stadium',124000.,85600,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30046,'USA','Omni Coliseum',42300.,31656,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30047,'USA','Orange Bowl',86520.,72700,'Miami, Florida');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30048,'USA','RFK Memorial Stadium',75420.,56500,'Washington, DC');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30049,'USA','Sanford Stadium',39520.,86100,'Athena, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30050,'USA','Stone Mountain Park Archery Center and Velodrome',42000.,11200,'Stone Mountain, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30051,'USA','Stone Mountain Park Tennis Center',34150.,27500,'Stone Mountain, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30052,'USA','University of Georgia Coliseum',35000.,10000,'Athena, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30053,'USA','Wassaw Sound',11000.,1000,'Savannah, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30054,'USA','Wolf Creek Shooting Complex',25000.,7500,'Atlanta, Georgia');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30055,'KOR','Seoul Olympic Stadium',75469.,100000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30056,'KOR','Jamsil Gymnasium',7098.,20000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30057,'KOR','Jamsil Indoor Swimming Pool',8073.,8000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30058,'KOR','Jamsil Students'' Gymnasium',11471.,7200,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30059,'KOR','Jamsil Baseball Stadium',26331.,30500,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30060,'KOR','Olympic Velodrome',5148.,6000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30061,'KOR','Olympic Fencing Gymnasium',8750.,7000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30062,'KOR','Olympic Weightlifting Gymnasium',5617.,3500,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30063,'KOR','Olympic Gymnastics Hall',11800.,15000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30064,'KOR','Olympic Tennis Courts',29064.,10000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30065,'KOR','Olympic Swimming Pool',12742.,10000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30066,'KOR','Hwarang Archery Field',35000.,7500,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30067,'KOR','Seoul Equestrian Park ',27000.,30000,'Gwacheon, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30068,'KOR','Wondang Ranch',35000.,10000,'Goyang, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30069,'KOR','Dongdaemun Stadium',95764.,22700,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30070,'KOR','Saemaul Sports Hall',37500.,15000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30071,'KOR','Changchung Gymnasium',5527.,5000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30072,'KOR','Royal Bowling Center',15000.,5000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30073,'KOR','Modern Pentathlon Stadium',25000.,10000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30074,'KOR','Daejeon Stadium',34000.,7500,'Daejeon, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30075,'KOR','Gwangju Stadium',12023.,14600,'Gwangju, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30076,'KOR','Daegu Stadium',13843.,13000,'Daegu, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30077,'KOR','Busan Stadium',7810.,5000,'Busan, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30078,'KOR','Han River Regatta Course',57000.,25000,'Hanam, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30079,'KOR','Seongnam Stadium',35000.,10000,'Seongnam, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30080,'KOR','Suwon Gymnasium',2025.,9000,'Suwon, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30081,'KOR','Taenung International Shooting Range',18500.,8000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30082,'KOR','Seoul National University Gymnasium ',23000.,7500,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30083,'KOR','Hanyang University Gymnasium',20000.,8000,'Seoul, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30084,'KOR','Sangmu Gymnasium',25000.,10000,'Siheung, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30085,'KOR','Busan Yachting Center',31000.,8000,'Busan, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30086,'KOR','Sungkyunkwan University Gymnasium',25000.,6000,'Suwon, Gyeonggi-do, Korea');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30087,'ESP','A-17 motorway circuit',75840.,8000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30088,'ESP','Banyoles Lake',35000.,15000,'Banyoles, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30089,'ESP','Bernat Picornell pools',36540.,9000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30090,'ESP','Canal Olympic de Castelldefels',40000.,10000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30091,'ESP','Estacio del Nord',42000.,8500,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30092,'ESP','FC Barcelona Stadium',36000.,7000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30093,'ESP','Institut Nacional d''Educacio Fisica de Catalunya',65000.,15000,'Lleida, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30094,'ESP','L''Hospitalet Baseball Stadium',60000.,34000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30095,'ESP','Mollet shooting range',34210.,19000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30096,'ESP','Olympic Harbour',80200.,20000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30097,'ESP','Olympic Stadium',34650.,8000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30098,'ESP','Palau Blaugrana',52400.,4000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30099,'ESP','Palau de la Metal-lurgia',36500.,5400,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30100,'ESP','Palau d''Esports in Badalona',34000.,4500,'Badalona, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30101,'ESP','Palau d''Esports in Granollers',56000.,1800,'Granollers, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30102,'ESP','Palau Sant Jordi',27110.,17000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30103,'ESP','Parc del Segre',11200.,3000,'Lleida, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30104,'ESP','Pavello Club Joventut Badalona',15000.,2800,'Badalona, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30105,'ESP','Pavello de la Mar Bella',62000.,15000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30106,'ESP','Pavello de la Vall d''Hebron',56400.,3400,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30107,'ESP','Pavello L''Espanya Industrial',16240.,3100,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30108,'ESP','Real Club de Polo',34500.,4600,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30109,'ESP','Sant Sadurn d''Anoia circuit ',24100.,5000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30110,'ESP','Terrassa Hockey Stadium',31000.,4600,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30111,'ESP','The Velodrom',19000.,6000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30112,'ESP','Vall d''Hebron archery field',24000.,5800,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30113,'ESP','Vall d''Hebron tennis complex ',21000.,4000,'Barcelona, Catalonia, Spain');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30114,'GRE','Ano Liossia',34000.,12000,'Ano Liosia, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30115,'GRE','Ano Liossia Olympic Hall',35000.,9300,'Ano Liosia, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30116,'GRE','Athens Olympic Stadium ',120400.,71030,'Maroussi, Athens, Greece ');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30117,'GRE','Faliro Coastal Zone Olympic Complex',34650.,12171,'Faliro, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30118,'GRE','Fencing Hall',64810.,5000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30119,'GRE','Galatsi Olympic Hall',26500.,6500,'Galatsi, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30120,'GRE','Indoor Arena',34000.,5800,'Faliro, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30121,'GRE','Markopoulo Olympic Equestrian Centre',64000.,15000,'Markopoulo, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30122,'GRE','Markopoulo Olympic Shooting Centre',25000.,4000,'Markopoulo, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30123,'GRE','Nikaia Olympic Weightlifting Hall',34000.,5100,'Nikaia, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30124,'GRE','Olympic Aquatic Centre',42500.,11500,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30125,'GRE','Olympic Baseball Centre',34500.,6700,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30126,'GRE','Olympic Beach Volleyball Centre',35000.,7300,'Faliro, Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30127,'GRE','Olympic Hall',52400.,21000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30128,'GRE','Olympic Hockey Centre',24000.,5200,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30129,'GRE','Olympic Indoor Hall',34100.,18800,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30130,'GRE','Olympic Modern Pentathlon Centre',18000.,5000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30131,'GRE','Olympic Sailing Centre',9000.,1600,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30132,'GRE','Olympic Softball stadium',31000.,3400,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30133,'GRE','Olympic Stadium',54700.,13000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30134,'GRE','Olympic Velodrome',20000.,3300,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30135,'GRE','Panathinaiko Stadium',86300.,50000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30136,'GRE','Peristeri Olympic Boxing Hall',23000.,5600,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30137,'GRE','Schinias Olympic Rowing and Canoeing Centre',27000.,6700,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30138,'GRE','Athens Olympic Tennis Centre',12800.,3200,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30139,'GRE','Goudi Olympic Hall',21000.,5000,'Athens, Greece');
INSERT INTO "stadium"("code","nation_code","name","area","seats","address")VALUES(30140,'GRE','Vouliagmeni Olympic Centre',7024.,3400,'Athens, Greece');
