ALTER TABLE "athlete" DROP CONSTRAINT "idx_athlete_name";
ALTER TABLE "game" DROP CONSTRAINT "fk_game_athlete_code";
ALTER TABLE "game" DROP CONSTRAINT "fk_game_event_code";
ALTER TABLE "game" DROP CONSTRAINT "idx_game_game_date";
ALTER TABLE "participant" DROP CONSTRAINT "fk_participant_nation_code";
ALTER TABLE "participant" DROP CONSTRAINT "fk_participant_host_year";
DROP TABLE "athlete";
DROP TABLE "code";
DROP TABLE "event";
DROP TABLE "game";
DROP TABLE "history";
DROP TABLE "nation";
DROP TABLE "olympic";
DROP TABLE "participant";
DROP TABLE "record";
DROP TABLE "stadium";
DROP TABLE "test_binary";
DROP TABLE "test_hash_partition";
DROP TABLE "test_list_partition";
DROP TABLE "test_number";
DROP TABLE "test_range_partition";
DROP TABLE "test_set";
DROP TABLE "test_string";
DROP TABLE "test_time";
DROP VIEW "game_view";
DROP VIEW "participant_view";
DROP SERIAL "test_sequence";
